"use strict";

const GAMEPAD = {};

GAMEPAD[GAMEPAD_TYPE.DUAL_SHOCK_4] = {
	buttons: [
		BUTTON_TYPE.ACTION_DOWN,
		BUTTON_TYPE.ACTION_RIGHT,
		BUTTON_TYPE.ACTION_LEFT,
		BUTTON_TYPE.ACTION_UP,
		BUTTON_TYPE.L1,
		BUTTON_TYPE.R1,
		BUTTON_TYPE.L2,
		BUTTON_TYPE.R2,
		BUTTON_TYPE.SELECT,
		BUTTON_TYPE.START,
		BUTTON_TYPE.L3,
		BUTTON_TYPE.R3,
		BUTTON_TYPE.DPAD_UP,
		BUTTON_TYPE.DPAD_DOWN,
		BUTTON_TYPE.DPAD_LEFT,
		BUTTON_TYPE.DPAD_RIGHT,
		BUTTON_TYPE.SPECIAL1,
		BUTTON_TYPE.SPECIAL2,
	],
	axes: [
		BUTTON_TYPE.LEFT_AXES_X,
		BUTTON_TYPE.LEFT_AXES_Y,
		BUTTON_TYPE.RIGHT_AXES_X,
		BUTTON_TYPE.RIGHT_AXES_Y,
	],
};
